apiVersion: apps/v1
kind: Deployment
metadata:
  name: hxnyc_web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: hxnyc-web
        image: hxnyc_web:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: hxnyc_service
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30300